// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mibandDevice.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DeviceUUID is the strucutre of the incoming message
type DeviceUUID struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceUUID) Reset()         { *m = DeviceUUID{} }
func (m *DeviceUUID) String() string { return proto.CompactTextString(m) }
func (*DeviceUUID) ProtoMessage()    {}
func (*DeviceUUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc977901481d1942, []int{0}
}

func (m *DeviceUUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceUUID.Unmarshal(m, b)
}
func (m *DeviceUUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceUUID.Marshal(b, m, deterministic)
}
func (m *DeviceUUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceUUID.Merge(m, src)
}
func (m *DeviceUUID) XXX_Size() int {
	return xxx_messageInfo_DeviceUUID.Size(m)
}
func (m *DeviceUUID) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceUUID.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceUUID proto.InternalMessageInfo

func (m *DeviceUUID) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

// HeartBeats is to structure of outgoing message
type HeartBeats struct {
	Pulse                string   `protobuf:"bytes,1,opt,name=pulse,proto3" json:"pulse,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeats) Reset()         { *m = HeartBeats{} }
func (m *HeartBeats) String() string { return proto.CompactTextString(m) }
func (*HeartBeats) ProtoMessage()    {}
func (*HeartBeats) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc977901481d1942, []int{1}
}

func (m *HeartBeats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeats.Unmarshal(m, b)
}
func (m *HeartBeats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeats.Marshal(b, m, deterministic)
}
func (m *HeartBeats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeats.Merge(m, src)
}
func (m *HeartBeats) XXX_Size() int {
	return xxx_messageInfo_HeartBeats.Size(m)
}
func (m *HeartBeats) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeats.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeats proto.InternalMessageInfo

func (m *HeartBeats) GetPulse() string {
	if m != nil {
		return m.Pulse
	}
	return ""
}

func (m *HeartBeats) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceUUID)(nil), "main.DeviceUUID")
	proto.RegisterType((*HeartBeats)(nil), "main.HeartBeats")
}

func init() { proto.RegisterFile("mibandDevice.proto", fileDescriptor_dc977901481d1942) }

var fileDescriptor_dc977901481d1942 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcd, 0x4c, 0x4a,
	0xcc, 0x4b, 0x71, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x52, 0xe0, 0xe2, 0x82, 0x88, 0x86, 0x86, 0x7a, 0xba, 0x08, 0x09,
	0x71, 0xb1, 0x80, 0x68, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0xc9, 0x82, 0x8b,
	0xcb, 0x23, 0x35, 0xb1, 0xa8, 0xc4, 0x29, 0x35, 0xb1, 0xa4, 0x58, 0x48, 0x84, 0x8b, 0xb5, 0xa0,
	0x34, 0xa7, 0x38, 0x15, 0xaa, 0x04, 0xc2, 0x01, 0x89, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x49, 0x30,
	0x41, 0x44, 0xc1, 0x1c, 0x23, 0x77, 0x2e, 0x1e, 0x5f, 0x24, 0x7b, 0x85, 0xcc, 0xb9, 0x78, 0xdd,
	0x53, 0x4b, 0x90, 0x0c, 0x13, 0xd0, 0x03, 0xb9, 0x41, 0x0f, 0xe1, 0x00, 0x29, 0xa8, 0x08, 0x42,
	0x8d, 0x12, 0x83, 0x01, 0x63, 0x12, 0x1b, 0xd8, 0xc5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x49, 0xd7, 0x79, 0xf7, 0xc7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MibandDeviceClient is the client API for MibandDevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MibandDeviceClient interface {
	GetHeartBeats(ctx context.Context, in *DeviceUUID, opts ...grpc.CallOption) (MibandDevice_GetHeartBeatsClient, error)
}

type mibandDeviceClient struct {
	cc *grpc.ClientConn
}

func NewMibandDeviceClient(cc *grpc.ClientConn) MibandDeviceClient {
	return &mibandDeviceClient{cc}
}

func (c *mibandDeviceClient) GetHeartBeats(ctx context.Context, in *DeviceUUID, opts ...grpc.CallOption) (MibandDevice_GetHeartBeatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MibandDevice_serviceDesc.Streams[0], "/main.MibandDevice/GetHeartBeats", opts...)
	if err != nil {
		return nil, err
	}
	x := &mibandDeviceGetHeartBeatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MibandDevice_GetHeartBeatsClient interface {
	Recv() (*HeartBeats, error)
	grpc.ClientStream
}

type mibandDeviceGetHeartBeatsClient struct {
	grpc.ClientStream
}

func (x *mibandDeviceGetHeartBeatsClient) Recv() (*HeartBeats, error) {
	m := new(HeartBeats)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MibandDeviceServer is the server API for MibandDevice service.
type MibandDeviceServer interface {
	GetHeartBeats(*DeviceUUID, MibandDevice_GetHeartBeatsServer) error
}

// UnimplementedMibandDeviceServer can be embedded to have forward compatible implementations.
type UnimplementedMibandDeviceServer struct {
}

func (*UnimplementedMibandDeviceServer) GetHeartBeats(req *DeviceUUID, srv MibandDevice_GetHeartBeatsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetHeartBeats not implemented")
}

func RegisterMibandDeviceServer(s *grpc.Server, srv MibandDeviceServer) {
	s.RegisterService(&_MibandDevice_serviceDesc, srv)
}

func _MibandDevice_GetHeartBeats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeviceUUID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MibandDeviceServer).GetHeartBeats(m, &mibandDeviceGetHeartBeatsServer{stream})
}

type MibandDevice_GetHeartBeatsServer interface {
	Send(*HeartBeats) error
	grpc.ServerStream
}

type mibandDeviceGetHeartBeatsServer struct {
	grpc.ServerStream
}

func (x *mibandDeviceGetHeartBeatsServer) Send(m *HeartBeats) error {
	return x.ServerStream.SendMsg(m)
}

var _MibandDevice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.MibandDevice",
	HandlerType: (*MibandDeviceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHeartBeats",
			Handler:       _MibandDevice_GetHeartBeats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mibandDevice.proto",
}
